version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    networks:
      - app-network

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - order-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge