spring:
  cloud:
    # 注意：写在远程配置里才生效（用于激活本地配置有效，便于开发使用）
    config:
      allow-override: true       # 允许本地配置覆盖远程配置
      override-none: true        # 本地配置文件、环境变量等可以覆盖远程配置
      override-system-properties: false  # 禁止系统属性（-D参数）覆盖远程配置